[build]
  publish = "dist"
  command = "vite build --config netlify-vite.config.ts"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev:frontend"
  port = 3000
  publish = "dist" 